[package]
name = "ares"
version = "0.1.0"
authors = ["Digant C Kasundra <diggyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"postgres" = "0.17.4"

[dev-dependencies]
mockall = "0.7.1"